### ISSUE TITLE
SSL endpoints not working in iOS

### ISSUE THREAD

**Issue by jbatra-umeey** [splitio/ios-client#381] opened 2022-10-17 05:54 UTC
I am trying to set https endpoint in `SplitClientConfig` serviceEndpoints but there is a SSL handshake issue for which there is no provision to handle

```
 var env = SPlitIOEnv()
 env.splitApiUrl = "https://xxx/split/sdk/api"
 env.splitEventsUrl = "https://xxx/split/events"
 env.splitAuthenticationUrl = "https://xxx/split/auth/api"
 env.splitStreamingUrl = "https://xxx/split/streaming/sse"
        
 let splitConfig = SplitClientConfig()
 splitConfig.serviceEndpoints = endpoints
```

As per the implementation in ` DefaultHttpRequestManager`, there is no method to handle `URLAuthenticationChallenge`. Hence, I added one to bypass SSL handshake for the time being

```
// MARK: HttpUrlSessionDelegate - URLSessionDataDelegate
extension DefaultHttpRequestManager: URLSessionDataDelegate {
  
    func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
          //Hack to trust the certificate even if not valid
          let urlCredential = URLCredential(trust: challenge.protectionSpace.serverTrust!)
          completionHandler(.useCredential, urlCredential)
       }
}
 ```
 
 On the contrary, there is no issue in Android. 
 Also I see  `.enableSslDevelopmentMode() ` in Android docs. Equivalent for this is not available in iOS

**Comment by chillaq** [comment] 2022-10-17 23:42
Hi @jbatra-umeey , thanks for the info, you are right, we do not have additional Auth/SSL parameters when overwriting the SDK urls.

I will submit a feature request on your behalf to handle  URLAuthenticationChallenge, could you please let me know which company you are working for? This helps when the issue is prioritized.

Thanks

**Comment by jbatra-umeey** [comment] 2022-10-26 13:01
@chillaq for now,  I would request you to consider this as an individual request. 
I have informed the concerned team in my organisation to use this ticket as a reference while contacting the support team. 
In addition, I would request you to please expedite the request so that the changes could be pushed to production

**Comment by chillaq** [comment] 2022-10-27 21:24
Hi @jbatra-umeey, thanks for the info. I submitted the Feature Request, our product managers go through the new features backlog frequently and will decide if it will be included in a certain version.
We do post all new features in our New Releases page (https://www.split.io/releases/) when they are released, I recommend to subscribe to the page for new updates.

**Closed by chillaq** 2022-10-27 21:24 UTC
