### ISSUE TITLE
Crash reported in $s5Split26DefaultBackoffCounterTimerC6cancelyyF on iOS 14 after updating split to 2.7

### ISSUE THREAD

**Issue by gsbernstein** [splitio/ios-client#204] opened 2020-12-10 18:23 UTC
Crashyltics reporting crash, steps to reproduce unknown.
Only reported in iOS 14
First event Nov 18, 2020

`EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000002100a011c
$s5Split26DefaultBackoffCounterTimerC6cancelyyF`

```
Crashed: pushMananagerMessagerQueue
0  libobjc.A.dylib                0x1984c0810 objc_destructInstance + 32
1  libswiftCore.dylib             0x187e8b580 swift_deallocClassInstance + 84
2  libswiftCore.dylib             0x187e8b420 _swift_release_dealloc + 40
3  Split                          0x1060e1d6c $s5Split26DefaultBackoffCounterTimerC6cancelyyF + 72
4  Split                          0x106161c24 $s5Split18DefaultSyncManagerC6handle33_C8732F0E9D57ED325882DC93904C1607LL9pushEventyAA010PushStatusN0O_tF + 236
5  Split                          0x106131f18 $s5Split15PushStatusEventOIegy_ACytIegnr_TRTA + 24
6  Split                          0x106131a0c $s5Split34DefaultPushManagerEventBroadcasterC4push5eventyAA0c6StatusE0O_tFyycfU_ + 100
7  Split                          0x1060efe50 $sIeg_IeyB_TR + 20
8  libdispatch.dylib              0x183b4724c _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x183b48db0 _dispatch_client_callout + 20
10 libdispatch.dylib              0x183b4c12c _dispatch_continuation_pop + 416
11 libdispatch.dylib              0x183b4b854 _dispatch_async_redirect_invoke + 592
12 libdispatch.dylib              0x183b5993c _dispatch_root_queue_drain + 356
13 libdispatch.dylib              0x183b5a120 _dispatch_worker_thread2 + 116
14 libsystem_pthread.dylib        0x1cd36c7c8 _pthread_wqthread + 216
15 libsystem_pthread.dylib        0x1cd37375c start_wqthread + 8
```

This appeared after updating from 2.6 to 2.7

**Comment by chillaq** [comment] 2020-12-11 00:15
Thanks @gsbernstein, how many crashes do you see from apps per day?

**Comment by gsbernstein** [comment] 2020-12-15 00:29
It represents 3 out of our top 10 crashes in the past week. Here's a screenshot of the last 7 days.
<img width="811" alt="Screen Shot 2020-12-14 at 4 21 36 PM" src="https://user-images.githubusercontent.com/6655924/102151772-7192eb80-3e28-11eb-9a68-0d72fa787288.png">
So 19 users /7d or 2.7 users per day. Not our biggest crash but enough that we likely won't update again until it's resolved, though the sporadic nature means it would be hard to confirm it's resolved until we start seeing it in the wild again.

**Comment by chillaq** [comment] 2020-12-16 18:55
Hi @gsbernstein, We are not able to reproduce the issue yet. It seems to be something that happen when streaming is available again after being down. 

Besides being reported only in iOS 14.. Does it occur in a particular device?

What is the app doing when the crash occurs?

Could we have the Split SDK integration code? It would help us to reproduce the scenario where the crash happen.

**Comment by gsbernstein** [comment] 2021-01-11 20:03
Sorry just realized I needed to reply.
-The main copy of the crash reports only iPhone by the time we yanked the plug but we have very limited iPad support. Lots of different devices within that though. 
<img width="463" alt="Screen Shot 2021-01-11 at 12 56 56 PM" src="https://user-images.githubusercontent.com/6655924/104231633-1ee72800-5404-11eb-8fce-949f034cfc97.png">
One of the other variants of the crash had a case on the 6th gen iPad though.

Our logging does not indicate any specific pattern in what's going on, but crashyltics reports 0% background

here's the bulk of our code:
```
//
//  Created by Brice Pollock on 10/2/18.
//  Copyright © 2018 Vida. All rights reserved.
//

import Foundation
import Split
import RxSwift
import VidaCore
import VidaLogger

class SplitWrapper {
    static let shared = SplitWrapper()

    private static let apiKey = ApiConstants().splitSDKKey
    internal static var deviceID: String {
        return UIDevice.current.identifierForVendor?.uuidString.lowercased() ?? "UNKNOWN_DEVICE_ID"
    }

    private static var defaultConfig: SplitClientConfig {
        return SplitClientConfig()
    }

    private var deviceFactory: SplitFactory
    private var userFactory: SplitFactory?
    private var userUUIDInFactory: String?

    public var client: SplitClient {
        if !shouldForceDeferToDeviceClient, let userClient = userClient {
            verboseLog("using userClient for split")
            return userClient
        }
        verboseLog("using deviceClient for split")
        return deviceClient
    }

    public var manager: SplitManager {
        return userFactory?.manager ?? deviceFactory.manager
    }

    // Provides treatments based upon deviceID
    internal var deviceClient: SplitClient {
        return deviceFactory.client
    }

    // Provides treatments based upon userID
    internal var userClient: SplitClient? {
        return userFactory?.client
    }

    public var waitForSplitObservable: Observable<Bool>?
    
    private var shouldForceDeferToDeviceClient = false {
        didSet {
            debugLog("shouldForceDeferToDeviceClient: \(shouldForceDeferToDeviceClient)")
        }
    }

    internal init() {
        let deviceKey = Key(matchingKey: SplitWrapper.deviceID)
        let config = SplitWrapper.defaultConfig
        config.trafficType = "deviceid"
        deviceFactory = DefaultSplitFactoryBuilder()
            .setApiKey(SplitWrapper.apiKey)
            .setKey(deviceKey)
            .setConfig(config)
            .build()!

        // App Delegate will use this observable to wait for the split client
        waitForSplitObservable = waitForClientIfNeededObservable()

        let trackingUUID = trackSplitClientCreated()
        deviceClient.on(event: SplitEvent.sdkReady) { [weak self] in
            guard let strongSelf = self else { return }
            strongSelf.trackSplitClientReady(trackingID: trackingUUID, success: true)
            debugLog("[Split] Device client updated from server. Sees \(strongSelf.deviceFactory.manager.splitNames.count) splits")
        }

        deviceClient.on(event: SplitEvent.sdkReadyTimedOut) { [weak self] in
            self?.trackSplitClientReady(trackingID: trackingUUID, success: false)
            errorLog("[Split] Device client failed to pull from server")
        }
    }

    func resetWaitForSplitObservable() {
        // App Delegate will use this observable to wait for the split client
        waitForSplitObservable = waitForClientIfNeededObservable()
        // Clean up the observable afterwards so we do not incur the async cost if no need to wait
        // We do not need to dispose because the observable will dispose itself onComplete
        _ = waitForSplitObservable?.subscribeOnNext { [weak self] (didSucceed) in
            self?.waitForSplitObservable = nil
        }
    }

    func updateUserURI(_ userURI: String?) {
        guard let uri = userURI else {
            userUUIDInFactory = nil
            userFactory = nil
            return
        }

        // When we logout we clear out user defaults. So when we login, we should make sure we reset the user defaults
        UserDefaults.standard.recordAppVersionNumber()

        // Note that Swift and Objective-C do not follow the UUID spec. They incorrectly return uppercase
        // uuid strings. See (https://tools.ietf.org/html/rfc4122#section-3 and https://bugs.swift.org/browse/SR-865)
        guard let userUUID = UUID(resourceUriid: uri)?.uuidString.lowercased() else {
            errorLog("invalid user UUID, cannot create split client")
            return
        }

        guard userUUIDInFactory != userUUID else {
            debugLog("Skipping updateUserURI because provided existing UUID")
            return
        }

        // matching
        let userKey = Key(matchingKey: userUUID)
        let config = SplitWrapper.defaultConfig
        config.trafficType = "user"
        debugLog("[Split] Using key: \(userUUID)")
        userUUIDInFactory = userUUID
        shouldForceDeferToDeviceClient = true
        userFactory = DefaultSplitFactoryBuilder()
            .setApiKey(SplitWrapper.apiKey)
            .setKey(userKey)
            .setConfig(config)
            .build()

        let trackingUUID = trackSplitClientCreated()
        userClient?.on(event: SplitEvent.sdkReady) { [weak self] in
            guard let strongSelf = self else { return }
            strongSelf.shouldForceDeferToDeviceClient = false
            strongSelf.trackSplitClientReady(trackingID: trackingUUID, success: true)
            debugLog("[Split] Update User client updated from server for \(userUUID). Sees \(String(describing: strongSelf.userFactory?.manager.splitNames.count ?? 0)) splits")
        }

        userClient?.on(event: SplitEvent.sdkReadyTimedOut) { [weak self] in
            self?.trackSplitClientReady(trackingID: trackingUUID, success: false)
            errorLog("[Split] Update User client failed to pull from server")
        }
    }

    /***
        This method is here to enable us to wait for the split client if necessary

        It gives a best effort to ensure that first time experience for users (on first launch) is as expected according to split configurations.

     Note: This complex strategy is required because Split's async processing also happens on main thread. Therefore if we held main thread
            waiting for the response... We'd always get notified of 'sdkReady' afterwards since the 'sdkReady' event would be async queued on our
            waiting main thread.
     ***/
    func waitForClientIfNeededObservable() -> Observable<Bool>? {
        guard let userURI = LoginManager.shared.currentUser?.resourceURIID else {
            return waitForClient(deviceClient)
        }
            
        updateUserURI(userURI)

        guard let userClient = userClient else {
            return waitForClient(deviceClient)
        }

        // we have a split that needs to update on launch so wait on user client
        return waitForClient(userClient)
    }

    func waitForClient(_ client: SplitClient) -> Observable<Bool> {
        // Note: We add our own timeout, since we use a workaround for our Split configuration.
        let timeoutInterval: DispatchTimeInterval = .seconds(1)
        return Observable
            .create { (observer) -> Disposable in
                client.on(event: SplitEvent.sdkReady) { [weak self] in
                    observer.onNext(true)
                    debugLog("[Split] Client updated from server. Sees \(String(describing: self?.deviceFactory.manager.splitNames.count ?? 0)) splits")
                    observer.onCompleted()
                }
                client.on(event: SplitEvent.sdkReadyTimedOut) {
                    errorLog("[Split] Client failed to pull from server")
                    observer.onNext(false)
                    observer.onCompleted()
                }
                return Disposables.create()
            }.share()
            .timeout(timeoutInterval, scheduler: MainScheduler.instance)
            .catchError({ (error) -> Observable<Bool> in
                debugLog("Split hit Vida timeout for client before ready")
                return Observable.just(false)
            })
    }

    private func trackSplitClientCreated() -> UUID {
        guard let request = fakeSplitRequest() else { return UUID() }
        return PerformanceTracker.shared.trackRequestSend(request)
    }

    private func trackSplitClientReady(trackingID: UUID, success: Bool) {
        guard let request = fakeSplitRequest() else { return }
        PerformanceTracker.shared.trackRequestResponse(request, trackingID: trackingID, success: success)
    }

    private func fakeSplitRequest() -> NSMutableURLRequest? {
        guard let URL = URL(string: "split.io") else { return nil }
        return NSMutableURLRequest(url: URL)
    }
}
```

```
//  Created by Axel Ancona Esselmann on 1/11/18.
//  Copyright © 2018 Vida. All rights reserved.
//

import Foundation
import VidaCore
import FirebaseCrashlytics
import VidaLogger

class MainAppExperiments: ExperimentClient {
    
    /// This property can be used to communicate to any systems activated by the Experiment client initialization to
    /// ignore requesting new experiments for the time being. Otherwise we create a cycle where to initialize the Experiment
    /// client, you need to check the current value of an experiment in that client.
    public private(set) static var isInitializing = true
    
    // Swap out this variable to mock out the experiments for tests
    var splitWrapper: SplitWrapper
    private let attributeHelper: SplitAttributeHelper
    
    var stateHistory = [String: String]()
    
    init(splitWrapper: SplitWrapper = SplitWrapper.shared) {
        let buildVersion = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "Unknown"
        let buildNumber = Bundle.main.object(forInfoDictionaryKey: kCFBundleVersionKey as String) as? String ?? "Unknown"
        
        attributeHelper = SplitAttributeHelper(buildVersion: buildVersion, buildNumber: buildNumber)
        
        // initialize the split client to set up its factories and pull split
        self.splitWrapper = splitWrapper
        
        // Clean up the observable afterwards so we do not incur the async cost if no need to wait
        // We do not need to dispose because the observable will dispose itself onComplete
        _ = splitWrapper.waitForSplitObservable?.subscribeOnNext({ [weak self] (didSucceed) in
            self?.splitWrapper.waitForSplitObservable = nil
        })
        MainAppExperiments.isInitializing = false
    }
    
    /** For any splits you want to sticky for the in-memory session of the application, assign to immutable variables here **/
    // Ex: lazy var someExperiment = { experimentClient.shouldShowExperiment(.some) }()
    
    // MARK: Public API
    
    func shouldShowExperiment<T: RawRepresentable>(_ experiment: T) -> Bool where T.RawValue == String {
        return shouldShowExperiment(experiment, splitCases: [.show])
    }
    
    func shouldShowExperiment<T: RawRepresentable>(_ experiment: T, splitCases: [SplitResponse]) -> Bool where T.RawValue == String {
        
        let logResult: String
        
        defer {
            Crashlytics.crashlytics().setCustomValue(logResult, forKey: "一split." + experiment.rawValue)
            logIfFirstOrChanged(key: experiment.rawValue, value: logResult)
        }
        
        if let overrideValue = SplitOverrideManager.shared.shouldShowExperiment(experiment) {
            logResult = "override " + String(overrideValue)
            return overrideValue
        }
        
        guard doesSplitExist(experiment.rawValue) else {
            logResult = "does not exist"
            return splitCases.contains(.unknown)
        }
        
        let experimentValue = splitWrapper.client.getTreatment(experiment.rawValue, attributes: attributeHelper.globalAttributes)
        guard let splitResponse = SplitResponse(rawValue: experimentValue) else {
            logResult = "unparseable (\(experimentValue))"
            return splitCases.contains(.unknown)
        }
        logResult = experimentValue
        return splitCases.contains(splitResponse)
    }
    
    func getConfig<T: RawRepresentable, R: Decodable>(_ experiment: T) -> R? where T.RawValue == String {
        let result = splitWrapper.client.getTreatmentWithConfig(experiment.rawValue)
        
        guard let configString = result.config else {
            logIfFirstOrChanged(key: experiment.rawValue, value: "no config")
            return nil
        }
        
        guard let configData = configString.data(using: .utf8) else {
            logIfFirstOrChanged(key: experiment.rawValue, value: "unparseable config (\(configString))")
            return nil
        }
        
        logIfFirstOrChanged(key: experiment.rawValue, value: configString)
        
        return try? JSONDecoder().decode(R.self, from: configData)
    }
    
    @objc func updateUserClient(_ userURI: String?) {
        splitWrapper.updateUserURI(userURI)
    }
    
    private let historyLock = NSRecursiveLock()
    private func logIfFirstOrChanged(key: String, value: String) {
        historyLock.lock()
        guard stateHistory[key] != value else {
            historyLock.unlock()
            return
        }
        stateHistory[key] = value
        historyLock.unlock()
        Crashlytics.crashlytics().log("split '\(key)' was '\(value)'")
    }
    
}

extension MainAppExperiments {
    func doesSplitExist(_ splitName: String) -> Bool {
        return splitWrapper.manager.splitNames.contains(splitName)
    }
}
```

Let me know if there's anything else I can provide

**Comment by gsbernstein** [comment] 2021-01-11 20:06
Also for completeness
```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        SubscribeToVidaLogger(disposeBag: disposeBag).start()
        initializeSplitSingleton()
        voipPushHelper.voipRegistration()
        return true
    }
    
    func initializeSplitSingleton() {
        if isUnitTesting() {
            // TODO - use mock
            Experiments.setShared(MainAppExperiments())
        } else {
            Experiments.setShared(MainAppExperiments())
        }
    }
```
and
```
//
//  ExperimentWrapper.swift
//
//  Created by Eric Groom on 10/1/19.
//  Copyright © 2019 CocoaPods. All rights reserved.
//

import Foundation

public protocol ExperimentClient {
    func shouldShowExperiment<T: RawRepresentable>(_ experiment: T, splitCases: [SplitResponse]) -> Bool where T.RawValue == String
    func updateUserClient(_ userURI: String?)
    func getConfig<T: RawRepresentable, R: Decodable>(_ experiment: T) -> R? where T.RawValue == String
}

public class Experiments {
    
    private static var shared: ExperimentClient!
    
    public static func setShared(_ client: ExperimentClient) {
        shared = client
    }
    
    public static func shouldShowExperiment<T>(_ experiment: T, splitCases: [SplitResponse] = [.show]) -> Bool where T: RawRepresentable, T.RawValue == String {
        return shared.shouldShowExperiment(experiment, splitCases: splitCases)
    }

    public static func updateUserClient(_ userURI: String?) {
        shared.updateUserClient(userURI)
    }
    
    public static func getConfig<T: RawRepresentable, R: Decodable>(_ experiment: T) -> R? where T.RawValue == String {
        shared.getConfig(experiment)
    }

}

public func shouldShowExperiment<T>(_ experiment: T, splitCases: [SplitResponse] = [.show]) -> Bool where T: RawRepresentable, T.RawValue == String {
    return Experiments.shouldShowExperiment(experiment, splitCases: splitCases)
}

```

**Comment by chillaq** [comment] 2021-02-26 23:19
Hi Greg, SDK iOS version 2.9.0 is released with a fix for this issue.

Thanks
Bilal

**Closed** 2021-03-05 15:52 UTC
