### ISSUE TITLE
Background task duration obj-c exception

### ISSUE THREAD

**Issue by gsbernstein** [splitio/ios-client#228] opened 2021-03-16 17:29 UTC
Since updating to 2.9 from 2.6 I've started seeing the following exception in console frequently while debugging. It is also being caught by an objective-c exception breakpoint I have enabled that shows the location as Line 46 of `CoreDataHelper.swift` in the split pod.

In console:
`[BackgroundTask] Background Task 2085 ("CoreData: Executing write request"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`

Breakpoint location (Line 46 is highlighted of `CoreDataHelper.swift`):
<img width="629" alt="Screen Shot 2021-03-16 at 10 21 22 AM" src="https://user-images.githubusercontent.com/6655924/111352401-5dd26d80-8641-11eb-95eb-75e4631cdf6f.png">

Breakpoint settings:
<img width="472" alt="Screen Shot 2021-03-16 at 10 22 09 AM" src="https://user-images.githubusercontent.com/6655924/111352506-793d7880-8641-11eb-8912-1056d4f030c8.png">

**Comment by chillaq** [comment] 2021-03-16 21:46
Hi @gsbernstein, thanks for the info, could you provide the code that uses the SDK on your app? I don't see the exception in my end.

**Comment by chillaq** [comment] 2021-03-17 15:25
Hi @gsbernstein,
In order to reproduce it and find a fix, we would need the following information:
- The config you're using to create the client
- The client integration source code (instantiation, wrapper, etc)
- Is the  SDK instantiated evaluating treatments when the app is in background? If that so, please share to us some details about technology, capabilities and source code if possible.
- Is the issue ocurring in all OS version and devices?
- Also, any other information that you consider relevant would be useful.
Please remeber you can send this data through support@split.io instead of pasting here.
Regards

**Comment by chillaq** [comment] 2021-04-08 18:35
Hi @gsbernstein, I am following up on this issue, could you please review the requested information above?

Thanks
Bilal

**Comment by chillaq** [comment] 2021-04-14 20:30
Hi @gsbernstein , It has been a while since I heard back from you, I am closing out this ticket. If there is still an open issue or if we can be of further assistance on this topic, feel free to respond to this thread and the ticket will be re-opened.

Thanks

Bilal

**Closed by chillaq** 2021-04-14 20:30 UTC
